Introduction_project/Introduction_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings 
from django.conf.urls.static import static
from introduction import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('picture/', views.picture, name='picture'),
    path('place/', views.place, name='place'),
    path('hobby/', views.hobby, name='hobby'),
    path('music/', views.music, name='music'),
    path('comment/', views.comment, name='comment'),
    path('update/<int:comment_id>', views.update, name='update'),
    path('delete/<int:comment_id>', views.delete, name='delete')
] 
#admin에서 사진을 눌렀을때 사진의 위치를 알고 띄울수있음
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Introduction_project/introduction/models.py
from django.db import models
from django.db.models.deletion import CASCADE


# Create your models here.

class Home(models.Model):
    name = models.CharField(max_length=20)
    greetings_1 = models.CharField(max_length=20)
    greetings_2 = models.CharField(max_length=20)
    picture = models.ImageField(upload_to='picture/', blank=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class About(models.Model):
    heading = models.CharField(max_length=50)
    career = models.CharField(max_length=20)
    description = models.TextField(blank=False)
    profile_img = models.ImageField(upload_to='profile/')
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.career


class Profile(models.Model):
    about = models.ForeignKey(About, on_delete=models.CASCADE)
    social_name = models.CharField(max_length=20)
    link = models.URLField(max_length=200)


class Category(models.Model):
    name = models.CharField(max_length=20)
    updated = models.DateTimeField(auto_now=True)

#Meta 왜쓰는 거였더라?!
    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'
    
    def __str__(self):
        return self.name

class Skills(models.Model):
    category = models.ForeignKey(Category, on_delete=CASCADE)
    skill_name = models.CharField(max_length=20)


class Portfolio(models.Model):
    image = models.ImageField(upload_to='portfolio/')
    link = models.URLField(max_length=200)

#아직 이해못했지만 일단 따라함
    def __str__(self):
        return f'Portfolio {self.id}'


class Hobby(models.Model):
    image = models.ImageField(upload_to='Hobby/')
    name = models.CharField(max_length=20)
    description = models.TextField(blank=False)
    
    def __str__(self):
        return self.name


class Music(models.Model):
    image = models.ImageField(upload_to='Music/', blank='True')
    singer = models.CharField(max_length=20)
    title = models.CharField(max_length=30)
    link = models.URLField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title

class Comment(models.Model):
    writer = models.CharField(max_length=20)
    write_date = models.DateTimeField()
    content = models.TextField(blank=False)

Introduction_project/introduction/views.py
from django.shortcuts import redirect, render
from .models import Category, Hobby, Home, About, Music, Portfolio, Profile, Comment
from django.utils import timezone

# Create your views here.
def index(request):

    # 가장 최근에 수정한 Home 인사말, 사진
    home = Home.objects.latest('updated')

    # 가장 최근 수정 프로필 
    about = About.objects.latest('updated')
    profile = Profile.objects.filter(about=about)   

    comments = Comment.objects.all()

    return render(request, 'index.html', {'home' : home, 'about' : about,'profile' : profile, 'comments':comments})

def comment(request):
    new_comment = Comment()
    new_comment.writer = request.POST['writer']
    new_comment.content = request.POST['content']
    new_comment.write_date = timezone.now()
    new_comment.save()

    return redirect('index')

def update(request, comment_id):
    if request.method == 'POST':
        comment = Comment.objects.get(id=comment_id)
        comment.writer = request.POST['writer']
        comment.content = request.POST['content']
        comment.write_date = timezone.now()
        comment.save()
        return redirect('index')
    else:
        comment = Comment.objects.get(id=comment_id)
        return render(request, 'update_comment.html', {'comment':comment})
        
def delete(request, comment_id):
    if request.method == 'POST':
        comment = Comment.objects.get(id=comment_id)
        comment.delete()
        return redirect('index')

def picture(request):
    pictures = Portfolio.objects.all()
    return render(request, 'my_pictures.html', {'pictures' : pictures})

def place(request):
    categories = Category.objects.all()
    return render(request, 'my_place.html', {'categories' : categories})


def hobby(request):
    hobbies = Hobby.objects.all()
    return render(request, 'my_hobby.html', {'hobbies' : hobbies})

def music(request):
    musics = Music.objects.all()
    return render(request, 'my_music.html', {'musics': musics})

Introduction_project/introduction/templates/base.html
<!--고유의 html 들어가는 구간-->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--title-->
    <title>{% block title %} {% endblock %}</title>

    <script src="https://kit.fontawesome.com/89e9803277.js" crossorigin="anonymous"></script>

    <!-- 합쳐지고 최소화된 최신 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- 부가적인 테마 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

    <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

    <!-- ===== BOX ICONS ===== -->
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>


    <style>
        /*===== GOOGLE FONTS =====*/
        
        @import url("https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700&display=swap");
        /*===== VARIABLES CSS =====*/
        
         :root {
            --header-height: 3rem;
            --font-medium: 500;
        }
        /*===== Colores =====*/
        
         :root {
            --first-color: #afaeff;
            --white-color: #FAFAFF;
            --dark-color: #2A3B47;
            --text-color: #697477;
        }
        /*===== 글꼴 =====*/
        
         :root {
            --body-font: 'Montserrat', sans-serif;
            --big-font-size: 6.25rem;
            --h2-font-size: 1.5rem;
            --normal-font-size: .938rem;
            --small-font-size: .813rem;
        }
        
        @media screen and (min-width: 768px) {
             :root {
                --big-font-size: 5rem;
                --h2-font-size: 2rem;
                --normal-font-size: 1rem;
                --small-font-size: .875rem;
            }
        }
        /*===== Margin =====*/
        
         :root {
            --mb-1: .5rem;
            --mb-2: 1rem;
            --mb-3: 1.5rem;
            --mb-4: 2rem;
        }
        /*===== z index =====*/
        
         :root {
            --z-fixed: 100;
        }
        /*===== BASE =====*/
        
        *,
         ::before,
         ::after {
            box-sizing: border-box;
        }
        
        html {
            scroll-behavior: smooth;
        }
        
        body {
            margin: var(--header-height) 0 0 0;
            font-family: var(--body-font);
            font-size: var(--normal-font-size);
            font-weight: var(--font-medium);
            color: var(--text-color);
            line-height: 1.6;
        }
        
        h1,
        h2,
        p {
            margin: 0;
        }
        
        ul {
            margin: 0;
            padding: 0;
            list-style: none;
        }
        
        a {
            text-decoration: none;
            color: var(--text-color);
        }
        
        img {
            /*꼭 필요*/
            max-width: 100%;
        }
        /*===== CLASS CSS ===== */
        
        .section {
            padding: 3rem 0;
        }
        
        .section-title {
            position: relative;
            font-size: rem;
            color: var(--dark-color);
            margin: var(--mb-4) 0;
            text-align: center;
            font-weight: bold;
        }
        
        .section-title::after {
            position: absolute;
            content: "";
            height: .28rem;
            left: 0;
            right: 0;
            margin: auto;
            margin-top: 0.8rem;
            background-color: var(--first-color);
        }
        /*===== LAYOUT =====*/
        
        .bd-grid {
            max-width: 1024px;
            display: grid;
            grid-template-columns: 100%;
            grid-column-gap: 2rem;
            width: calc(100% - 2rem);
            margin-left: var(--mb-2);
            margin-right: var(--mb-2);
        }
        
        .l-header {
            width: 100%;
            position: fixed;
            top: 0;
            left: 0;
            z-index: var(--z-fixed);
            background-color: var(--first-color);
        }
        /*===== HOME =====*/
        
        .home {
            position: relative;
            background-color: var(--first-color);
            overflow: hidden;
        }
        
        .home__container {
            height: calc(100vh - var(--header-height));
            row-gap: 5rem;
        }
        
        .home__title {
            align-self: flex-end;
            color: var(--white-color);
            font-size: 5rem;
            font-weight: bold;
        }
        
        .home__scroll {
            align-self: flex-end;
        }
        
        .home__scroll-link {
            writing-mode: vertical-lr;
            /*글씨 회전*/
            transform: rotate(-180deg);
            color: var(--white-color);
        }
        
        .home__img {
            position: absolute;
            transform: rotate(-5deg);
            bottom: 0;
        }
        /* ===== ABOUT =====*/
        
        .about__container {
            justify-items: center;
            row-gap: 2rem;
            text-align: center;
        }
        
        .about__img {
            display: flex;
            justify-content: center;
            background-color: var(--first-color);
            border-radius: 50%;
            overflow: hidden;
        }
        
        .about__subtitle {
            font-size: 3rem;
            font-weight: bold;
            color: var(--first-color);
            margin-bottom: var(--mb-1);
            margin-top: 0.8rem;
        }
        
        .about__profession {
            font-size: 2rem;
            margin-bottom: var(--mb-4);
        }
        
        .about__text {
            margin-bottom: var(--mb-4);
            margin-top: 2rem;
            font-size: 1.5rem;
        }
        
        .about__social-icon {
            font-size: 3rem;
            float: right;
        }
        
        .about__social-icon:hover {
            color: var(--first-color);
        }
        /* ===== Places =====*/
        
        .skills__subtitle {
            color: var(--first-color);
            font-weight: bold;
        }
        
        .skills__name {
            display: inline-block;
            text-align: center;
            font-size: 1.6rem;
            margin-right: var(--mb-2);
            margin-bottom: var(--mb-3);
            background-color: rgb(232, 238, 255);
            padding: .25rem .5rem;
            border-radius: .25rem;
        }
        
        .skills__name:hover {
            background-color: var(--first-color);
            color: whitesmoke;
        }
        /* ===== Pictures =====*/
        
        .portfolio__container {
            justify-items: center;
            row-gap: 2rem;
        }
        
        .portfolio__img {
            position: relative;
            overflow: hidden;
        }
        
        .portfolio__img img {
            border-radius: .5rem;
        }
        
        .portfolio__link {
            position: absolute;
            bottom: -100%;
            width: 100%;
            height: 50%;
            display: flex;
            justify-content: center;
            align-items: center;
            background-color: rgba(255, 255, 255, .3);
            border-radius: .5rem;
            cursor: pointer;
            backdrop-filter: blur(20px);
            transition: .3s;
        }
        /*이걸 해야 위치보는 화면이 등장함*/
        
        .portfolio__img:hover .portfolio__link {
            bottom: 0;
        }
        
        .portfolio__link-name {
            color: black;
        }
        /* ===== CONTACT =====*/
        
        .contact__container {
            row-gap: 2rem;
        }
        
        .contact__subtitle {
            font-size: var(--normal-font-size);
            color: var(--first-color);
        }
        
        .contact__text {
            display: inline-block;
            margin-bottom: var(--mb-2);
        }
        /* ===== FOOTER=====*/
        
        .footer {
            background-color: var(--dark-color);
        }
        
        .footer__container {
            row-gap: 2rem;
        }
        
        .footer__title {
            font-size: var(--normal-font-size);
            color: var(--white-color);
            margin-bottom: var(--mb-2);
        }
        
        .footer__link {
            padding: .25rem 0;
        }
        
        .footer__link:hover {
            color: var(--first-color);
        }
        
        .footer__social {
            font-size: 1.4rem;
            margin-right: var(--mb-1);
        }
        
        .footer__social:hover {
            color: var(--first-color);
        }
        /* ===== MEDIA QUERIES =====*/
        /* For small devices */
        
        @media screen and (max-width: 320px) {
            .home__img {
                width: 230px;
            }
        }
        
        @media screen and (min-width: 768px) {
            body {
                margin: 0;
            }
            .section {
                padding-top: 4rem;
            }
            .section-title {
                margin-bottom: 3rem;
            }
            .section-title::after {
                width: 64px;
                top: 3rem;
            }
            .nav {
                height: calc(var(--header-height) + 1rem);
            }
            .nav__list {
                display: flex;
            }
            .nav__item {
                margin-left: var(--mb-4);
                margin-bottom: 0;
            }
            .nav__toggle {
                display: none;
            }
            .nav__link {
                color: var(--white-color);
            }
            .nav__link:hover {
                color: var(--white-color);
            }
            .active::after {
                background-color: var(--white-color);
            }
            .home__container {
                height: 100vh;
                grid-template-rows: 1.7fr 1fr;
                row-gap: 0;
            }
            .home__img {
                width: 524px;
                right: 10%;
            }
            .about__container {
                grid-template-columns: repeat(2, 1fr);
                align-items: center;
                text-align: initial;
                padding: 4rem 0;
            }
            .about__img {
                width: 200px;
                height: 200px;
            }
            .about__img img {
                width: 165px;
            }
            .skills__container {
                grid-template-columns: repeat(2, 1fr);
                align-items: center;
            }
            .portfolio__container {
                grid-template-columns: repeat(3, 1fr);
                grid-template-rows: repeat(1, 1fr);
                column-gap: 2rem;
            }
            .contact__container {
                grid-template-columns: repeat(2, 1fr);
                justify-items: center;
            }
            .contact__form {
                width: 380px;
            }
            .footer__container {
                grid-template-columns: repeat(3, 1fr);
                justify-items: center;
            }
        }
        
        @media screen and (min-width: 1024px) {
            .bd-grid {
                margin-left: auto;
                margin-right: auto;
            }
        }
        /* For tall screens on mobiles y desktop*/
        
        @media screen and (min-height: 721px) {
            .home__container {
                height: 640px;
            }
            .home__img {
                width: 500px;
                right: 24%;
            }
        }
    </style>
</head>

<body>
    <!--=====NavBar=====-->
    <ul class="nav nav-pills" style="font-size: 1.5rem; height: 4.5rem;">
        <li role="presentation" style="float: right;"><a href="{% url 'index' %}">Home</a></li>
        <li role="presentation" style="float: right;"><a href="{% url 'picture' %}">my picture</a></li>
        <li role="presentation" style="float: right;"><a href="{% url 'place' %}">my place</a></li>
        <li role="presentation" style="float: right;"><a href="{% url 'music' %}">my music</a></li>
        <li role="presentation" style="float: right;"><a href="{% url 'hobby' %}">my hobby</a></li>
    </ul>

    {% block contents %} {% endblock %}

    <!--===== FOOTER =====-->
    <footer class="footer section">
        <div class="footer__container bd-grid">
            <div class="footer__data">
                <h2 class="footer__title">Kim Chae Eun</h2>
                <p class="footer__text">성신여자대학교 컴퓨터공학과 멋쟁이사자처럼 10기</p>
            </div>

            <div class="footer__data">
                <h2 class="footer__title">FOLLOW</h2>
                <a href="#" class="footer__social"><i class='bx bxl-instagram' >kimchaen1219</i></a>
            </div>
        </div>
    </footer>

</body>

</html>

Introduction_project/introduction/templates/index.html
{% extends 'base.html' %} {% block title %}멋사 10기 운영진 김채은을 소개합니다!{% endblock %} {% block contents %}
<main class="l-main">
    <!--===== HOME =====-->
    <section class="home" id="home">
        <div class="home__container bd-grid">
            <h1 class="home__title"><span>{{home.greetings_1}}</span><br><br>{{home.greetings_2}}</h1>

            <div class="home__scroll">
                <a href="#about" class="home__scroll-link"><i class='bx bx-up-arrow-alt' ></i>Scroll down</a>
            </div>
        </div>
    </section>

    <!--===== ABOUT ME =====-->
    <section class="about section" id="about">
        <h2 class="section-title">About ME</h2>

        <div class="about__container bd-grid">
            <div class="about__img" style="bottom: 0;">
                <img src="{{about.profile_img.url}}" alt="과잠입은 프로필 사진">
            </div>

            <div>
                <h2 class="about__subtitle">{{about.heading}}</h2>
                <span class="about__profession">{{about.career}}</span>
                <p class="about__text">{{about.description}}
                </p>

                <div class="about__social">
                    <!--github link-->
                    <a target="_blank" href="https://github.com/kimchaeeun3447" class="about__social-icon"><i class='bx bxl-github' ></i></a>
                </div>
            </div>
        </div>
    </section>

    <!--===== CONTACT =====-->
    <section class="contact section" id="contact">
        <h2 class="section-title">Contact Me</h2>
        <div class="contact__container bd-grid">
            <div class="contact__info">
                <h3 class="contact__subtitle" style="font-size: 1.5rem;">EMAIL</h3>
                <span class="contact__text" style="font-size: 1.5rem;">rlacodms3447@gmail.com</span>
                <h3 class="contact__subtitle" style="font-size: 1.5rem;">ADRESS</h3>
                <span class="contact__text" style="font-size: 1.5rem;">일산</span>

            </div>
        </div>

        <h2 class="section-title">방명록</h2>
        <h5 style="text-align: center;">심심하시면 방명록을 남겨주세요!</h5>

        {% for comment in comments%}

        <div class="about__container bd-grid" style="position: sticky; margin-bottom: -5rem;">
            <div style="border: 1px solid rgb(197, 196, 196); border-radius: 2%; padding: 5px; width: 120rem;">
                <span class="about__profession">{{comment.writer}}</span>
                <p class="about__text">{{comment.content}}</p>

                <form action="{% url 'update' comment.id %}" method="get">
                    {%csrf_token%}
                    <input type="submit" class="update_btn" name="update_btn" style="float: right; font-size: large;" value="수정">
                </form>

                <form action="{% url 'delete' comment.id %}" method="post">
                    {%csrf_token%}
                    <input type="submit" class="del_btn" name="del_btn" style="float: right; font-size: large;" value="삭제">

                </form>
            </div>

        </div>

        {%endfor%}
        <div class="about__container bd-grid" style="position: sticky;">
            <form action="{%url 'comment'%}" method="post">
                <div>
                    {%csrf_token%}
                    <label for="writer" style="font-size: 2rem;"> Name</label>
                    <input id="writer" type="text" name="writer" style="font-size: 2rem; margin-left: 22px;"><br>

                    <label for="content" style="font-size: 2rem;"> Content</label>
                    <textarea id="content" name="content" cols="100" rows="5" style="font-size: 2rem;"></textarea>
                    <button type="submit" style="font-size: 3rem;float: right; border: none; border-radius: 5px;  padding: 5px;background-color: lavender;">enter</button>
                </div>
            </form>
        </div>
    </section>
</main>
{% endblock %}

Introduction_project/introduction/templates/my_hobby.html
{% extends 'base.html' %} {% block title %}나의 취미{% endblock %} {% block contents %}
<!--===== 내 취미 =====-->
<section class="portfolio section" id="portfolio">
    <h2 class="section-title">My hobby</h2>
    <div class="portfolio__container bd-grid">
        {% for hobby in hobbies%}
        <div class="portfolio__img">
            <img src="{{hobby.image.url}}">
            <div>
                <h2 class="about__subtitle" style="text-align: center;font-size: 2.5rem;color: rgb(144, 130, 150);">{{hobby.name}}</h2>
                <p class="about__text" style="font-size: 1.5rem;">{{hobby.description}}</p>

            </div>
        </div>
        {%endfor%}
    </div>
</section>
{% endblock %}

Introduction_project/introduction/templates/my_music.html
{% extends 'base.html' %} {% block title %}나의 음악{% endblock %} {% block contents %}
<!--===== 내가 좋아하는 음악 =====-->
<section class="portfolio section" id="portfolio">
    <h2 class="section-title">My favorite Music</h2>

    <div class="portfolio__container bd-grid" style="margin-bottom: 5rem;">
        {% for music in musics%}
        <div class="portfolio__img" style="border: 1px solid rgb(187, 187, 187); border-radius: 3%; padding: 2rem;">
            <img src="{{music.image.url}}">
            <div>
                <h2 class="about__subtitle" style="text-align: center;font-size: 2.2rem;color: rgb(51, 51, 51);">{{music.singer}} - {{music.title}}</h2>
                <p class="about__text" style="font-size: 1.5rem;">{{music.description}}</p>
            </div>
            <div>
                <a target="_blank" href="{{music.link}}" style="float: right;"><i class="fab fa-youtube fa-2x"></i></a>
            </div>
        </div>
        {%endfor%}
    </div>
</section>
{% endblock %}

Introduction_project/introduction/templates/my_pictures.html
{% extends 'base.html' %} {% block title %}내가 찍은 사진{% endblock %} {% block contents %}
<!--===== 내가 찍은 사진 PORTFOLIO =====-->
<section class="portfolio section" id="portfolio">
    <h2 class="section-title">My Pictures</h2>
    <h5 style="text-align: center;">사진에 커서를 올리고 위치를 클릭해보세요!</h5>
    <div class="portfolio__container bd-grid">
        {% for picture in pictures%}
        <div class="portfolio__img">
            <img src="{{picture.image.url}}">

            <div class="portfolio__link">
                <a href="{{picture.link}}" class="portfolio__link-name">위치</a>
            </div>
        </div>
        {%endfor%}
    </div>
</section>
{%endblock%}

Introduction_project/introduction/templates/my_place.html
{% extends 'base.html' %} {% block title %}내가 좋아하는 장소{% endblock %} {% block contents %}
<!--===== Place =====-->
<section class="skills section" id="skills" style="height: 100%;">
    <h2 class="section-title">My favorite Places</h2>
    <div class="skills__container bd-grid">
        <div class="skills__box">
            {% for category in categories %}
            <h3 class="skills__subtitle">{{category.name}}</h3>
            {% for place in category.skills_set.all %}
            <span class="skills__name">{{place.skill_name}}</span> {%endfor%} {%endfor%}
        </div>
    </div>
</section>
{% endblock %}

Introduction_project/introduction/templates/update_comment.html
{% extends 'base.html' %} {% block title %}{% endblock %} {% block contents %}

<div class="about__container bd-grid" style="position: sticky;">
    <form action="{% url 'update' comment.id %}" method="post">
        <div>
            {%csrf_token%}
            <label for="writer" style="font-size: 2rem;"> Name</label>
            <input id="writer" type="text" name="writer" style="font-size: 2rem; margin-left: 22px;" value="{{comment.writer}}"><br>

            <label for="content" style="font-size: 2rem;"> Content</label>
            <textarea id="content" name="content" cols="100" rows="5" style="font-size: 2rem;">{{comment.content}}</textarea>
            <input type="submit" class="update_btn" name="update_btn" style="float: right; font-size: large;" value="수정">
        </div>
    </form>
</div>

{% endblock %}